### ISSUE TITLE
Missing HTTP method constants

### ISSUE THREAD

**Issue by XSven** [THEMA-MEDIA/HTTP-Method#2]
While searching for a module that exports (on request not per default) HTTP methods as constants that stringify to uppercase method names, I have found this module. I am missing GET as a shorthand for HTTP::Method->GET, etc.

**Comment by vanHoesel** [comment]
@XSven , I am happy surprised with your comment and had to think why I did not go for that.

As with `HTTP::Request::Common`, the 'common' method names are already used and imported into your namespace, but represent 'builders' for the various `HTTP::Requests` you like to have. So those already give you (by default) things like `GET` and `PUT`.

My approach was to avoid name-clashes and go for the explicit `HTTP::Method::GET` and `HTTP::Method::PUT` and so on.

Making the method names exportable via `@EXPORT_OK` would be okay, but it comes with the risk of confusing people that are familiar with the `HTTP::*` modules.

However, I will consider it, when people want to use it with the shortcut like
```perl
use HTTP::Method qw/GET PUT/;
```
apparently one knows what one is doing, and aware of the risks.

**Comment by XSven** [comment]
Thanks for the feedback.

These days when I use modules I am specifying the symbols to be imported always explicitly because some module authors still do not consider [Selecting What to Export](https://perldoc.perl.org/Exporter.html#Selecting-What-to-Export) properly. For me HTTP::Method should be considered an enumeration type and your implementation would fit completely, if you would make GET, etc. exportable on request (using @EXPORTER_OK). With the right warnings pragma configuration it should even be possible to get informed about name clashes.

**Comment by vanHoesel** [comment]
You are right, the `HTTP::Method::*` feels like enumeration.

Re-reading the advice on Exporting, it seems Idid not violate any, did I ? Since it is OO, nothing exported and the `HTTP::Method::*` methods are accessible, as always.

There are situations that I do export subroutines be default; when there are only a very few of them, with very explicit names and that you would most likely all need them when using the module. Other than that, I hate it to see 'things' appear in code, not knowing where they come from, so explicit import is what I usually do myself.

> With the right warnings pragma configuration it should even be possible to get informed about name clashes

Not sure what you are trying to say there.

Furthermore, I seen no problem to add the capitalised versions to a `@EXPORT_OK`, if that makes you more happy :-)

**Comment by XSven** [comment]
No you did not violate any of the advices on Exporting. Even if you add the capitalised versions to a `@EXPORT_OK` you would not violate the rule

"As a general rule, if the module is trying to be object oriented then export nothing."

This rule does NOT refer to the creation of aliases otherwise the `aliased` pragma would violate the rule which it does not.

If the `Exporter` module would have `warnings` of the category `redefine` enabled, users would be informed about name clashes. 

Although I like to be happy :-) it is up to you to introduce capitalised versions of `HTTP::Method::*`. It was a suggestion that should fit to the design of your module.

**Comment by vanHoesel** [comment]
Your feedback is very much appreciated
